version: "3"
services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - promnet

    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
            - '7071:7071'
        volumes:
            - ./files:/files
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - JMX_PORT=9999
            - KAFKA_OPTS=-javaagent:/files/jmx_prometheus_javaagent-0.6.jar=7071:/files/prometheus-config.yml
        depends_on:
            - zookeeper
        networks:
            - promnet


    prometheus:
        image: prom/prometheus
        user: root
        volumes:
            - ./config:/prometheus
            - ./data/prometheus:/data
        command:
            - '--config.file=/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/data'
        ports:
            - 9090:9090
        links:
            - kafka
        restart: always
        networks:
            - promnet

networks:
    promnet:
        driver: bridge



